version: '3.8'

services:
  postgresdb:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$PG_USER
      - POSTGRES_PASSWORD=$PG_PASS
      - POSTGRES_DB=$PG_DB
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgres
      - type: bind
        source: ./db
        target: /data

  app:
    depends_on:
      - postgresdb
    restart: always
    env_file:
      - .env
    environment:
      - PG_HOST=postgresdb
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=8083
    ports:
      - "8083:8083"
    platform: linux/amd64

volumes:
  db: