version: '3.8'

services:
  postgresdb:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$PG_USER
      - POSTGRES_PASSWORD=$PG_PASS
      - POSTGRES_DB=$PG_DB
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgres
      - ./sql/init.sql:/init.sql
    networks:
      - my_network

  app:
    depends_on:
      - postgresdb
    restart: always
    env_file:
      - .env
    environment:
      - PG_HOST=postgresdb
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=8083
    ports:
      - "8083:8083"
    platform: linux/amd64
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  db: